- labels:
    environment: lab
    service: api-gateway
  targets:
    - http://100.85.152.43:8000/health

- labels:
    environment: lab
    service: identity-service
  targets:
    - http://100.83.57.43:8020/health

- labels:
    environment: lab
    service: order-service
  targets:
    - http://100.108.225.1:8030/health

- labels:
    environment: lab
    service: catalog-service
  targets:
    - http://100.95.65.46:8040/health
