- labels:
    environment: lab
    service: identity-service
  targets:
    - http://100.83.57.43:8020/health

- labels:
    environment: lab
    service: order-service
  targets:
    - http://100.108.225.1:8030/health
