global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: blackbox-http-health
    metrics_path: /probe
    params:
      module:
        - http_2xx
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/microservices.yml
        refresh_interval: 30s
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: node-exporter
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/nodes.yml
        refresh_interval: 30s

  - job_name: api-gateway
    metrics_path: /metrics
    static_configs:
      - targets:
          - 100.85.152.43:8000
        labels:
          environment: lab
          service: api-gateway

  - job_name: microservices-metrics
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/app-metrics.yml
        refresh_interval: 30s
